name: Github Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  schedule:
    - cron: '0 5 * * *'

jobs:
  github-pages:
    runs-on: ubuntu-latest

    environment: github-pages

    steps:
      # /home/runner/work/centixkadon.github.io/centixkadon.github.io

      - name: Dump Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: |
          echo ${GITHUB_CONTEXT}
          echo ${JOB_CONTEXT}
          echo ${STEPS_CONTEXT}
          echo ${RUNNER_CONTEXT}
          echo ${STRATEGY_CONTEXT}
          echo ${MATRIX_CONTEXT}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Environment Linux
        run: uname --all

      - name: Environment Ubuntu
        run: lsb_release --all

      - name: Environment Docker
        run: docker --version

      - name: Git Log
        id: git-log
        run: echo "::set-output name=commit::$(git log --max-count=1 --pretty=%H%n%n%s)"

      - name: Cache Ruby
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-${{ hashFiles('Gemfile') }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-${{ hashFiles('Gemfile') }}-${{ hashFiles('Gemfile.lock') }}
            ${{ runner.os }}-ruby-

      - name: List Directories
        run: ls -alF

      - name: Git Clone
        env:
          github_pages_user: ${{ secrets.JEKYLL_GITHUB_PAGES }}
        run: |
          git clone --branch gh-pages --depth 1 https://${github_pages_user}@github.com/centixkadon/centixkadon.github.io.git _site
          chmod 777 _site

      - name: Jekyll Build
        run: |
          mkdir -p vendor/bundle
          chmod -R 777 vendor
          docker run --volume $(pwd):/srv/jekyll jekyll/builder:latest /bin/bash -c "bundle config set path vendor/bundle && bundle config set clean true && bundle install --jobs=4 --retry=3 && PAGES_REPO_NWO=centixkadon/centixkadon.github.io bundle exec jekyll build --future"

      - name: Git Push
        env:
          commit: ${{ steps.git-log.outputs.commit }}
        run: |
          cd _site
          git config --global user.name centixkadon
          git config --global user.email centixkadon@gmail.com
          git add .
          git commit --message "update: ${commit}"
          git push --force-with-lease
          cd -
