name: Github Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest

    environment: github-pages

    steps:
      - name: Show Directory
        run: pwd

      - name: Checkout
        uses: actions/checkout@v2

      # /home/runner/work/centixkadon.github.io/centixkadon.github.io

      - name: Environment Linux
        run: uname --all

      - name: Environment Ubuntu
        run: lsb_release --all

      - name: Environment Docker
        run: docker --version

      - name: Git Log
        id: git-log
        run: echo "::set-output name=commit::$(git log --max-count=1 --pretty=%s)"

      - name: Cache Ruby
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-${{ hashFiles('Gemfile') }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-${{ hashFiles('Gemfile') }}-${{ hashFiles('Gemfile.lock') }}
            ${{ runner.os }}-ruby-

      - name: List Directories
        run: ls -alF

      - name: Git Clone
        env:
          github_pages_user: ${{ secrets.JEKYLL_GITHUB_PAGES }}
        run: |
          git clone --branch gh-pages --depth 1 https://${github_pages_user}@github.com/centixkadon/centixkadon.github.io.git _site
          chmod 777 _site

      - name: Jekyll Build
        run: |
          mkdir -p vendor/bundle
          chmod -R 777 vendor
          docker run --volume $(pwd):/srv/jekyll jekyll/builder:latest /bin/bash -c "bundle config set path vendor/bundle && bundle install --jobs=4 --retry=3 --clean && PAGES_REPO_NWO=centixkadon/centixkadon.github.io bundle exec jekyll build --future"

      - name: Git push
        env:
          commit: ${{ steps.git-log.outputs.commit }}
        run: |
          cd _site
          git add .
          git commit -m "update for ${commit}"
          git push --force-with-lease
          cd -
