
name: Github Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  schedule:
    - cron: '0 5 * * *'

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_EVENT_NAME: ${{ github.event.pusher.name }}
  GITHUB_EVENT_EMAIL: ${{ github.event.pusher.email }}
  GITHUB_WORKSPACE: ${{ github.workspace }}

# directory /home/runner/work/centixkadon.github.io/centixkadon.github.io
# bash_account runner.docker
# docker_account runneradmin.runneradmin

jobs:
  github-pages:
    runs-on: ubuntu-latest

    environment: github-pages

    steps:
      - name: Dump Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: |
          echo github ${GITHUB_CONTEXT}
          echo job ${JOB_CONTEXT}
          echo steps ${STEPS_CONTEXT}
          echo runner ${RUNNER_CONTEXT}
          echo strategy ${STRATEGY_CONTEXT}
          echo matrix ${MATRIX_CONTEXT}

      - name: Environment Bash
        run: bash --version

      - name: Environment Linux
        run: uname --all

      - name: Environment Ubuntu
        run: lsb_release --all

      - name: Environment Git
        run: git --version

      - name: Environment Ruby
        id: ruby
        run: |
          ruby --version
          echo "::set-output name=version::$(ruby <<< puts\ RUBY_VERSION)"

      - name: Environment Docker
        run: docker --version

      - name: Checkout
        uses: actions/checkout@v2

      - name: Git Log
        id: git-log
        run: |
          echo commit-hash "$(git log --max-count=1 --pretty=%H)"
          echo commit-title "$(git log --max-count=1 --pretty=%s)"
          echo "::set-output name=commit-hash::$(git log --max-count=1 --pretty=%H)"
          echo "::set-output name=commit-title::$(git log --max-count=1 --pretty=%s)"

      - name: Cache Ruby
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-v${{ steps.ruby.outputs.version }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-v${{ steps.ruby.outputs.version }}-${{ hashFiles('Gemfile.lock') }}
            ${{ runner.os }}-ruby-v${{ steps.ruby.outputs.version }}-

      - name: Git Clone
        env:
          GITHUB_PAGES_USER: ${{ secrets.JEKYLL_GITHUB_PAGES }}
        run: |
          git clone --branch gh-pages --depth 1 https://${GITHUB_PAGES_USER}@github.com/${GITHUB_REPOSITORY}.git _site
          mkdir --parents empty
          rsync --recursive --del --exclude .git empty/ _site

      - name: Jekyll Build
        run: |
          mkdir --parents vendor/bundle
          chmod --recursive 777 vendor
          chmod 777 _site
          docker run --volume ${GITHUB_WORKSPACE}:/srv/jekyll jekyll/builder:latest /bin/bash -c "bundle config set path vendor/bundle && bundle config set clean true && bundle install --jobs=4 --retry=3 && PAGES_REPO_NWO=${GITHUB_REPOSITORY} bundle exec jekyll build --future"

      - name: Git Push
        env:
          COMMIT_HASH: ${{ steps.git-log.outputs.commit-hash }}
          COMMIT_TITLE: ${{ steps.git-log.outputs.commit-title }}
        run: |
          cd _site
          git config --global user.name "${GITHUB_EVENT_NAME}"
          git config --global user.email "${GITHUB_EVENT_EMAIL}"
          git add .
          git commit --message "update by ${COMMIT_HASH}

          ${COMMIT_TITLE}" || echo nothing to commit
          git push --force-with-lease

      - name: Show Directory
        run: pwd
